package com.dripdoggy.backend.enums;

import com.fasterxml.jackson.annotation.JsonFormat;

@JsonFormat(with = JsonFormat.Feature.ACCEPT_CASE_INSENSITIVE_VALUES)
public enum DeliveryStatus {
//    PLACED, CONFIRMED, SHIPPED, OUT_FOR_DELIVERY, DELIVERED, CANCELLED,

	PLACED,
	PROCESSING,
	PACKED,
	SHIPPED,
	OUT_FOR_DELIVERY,
	DELIVERED,
	CANCELLED,
	RETURN_INITIATED,
	RETURN_PICKUPED,
	RETURN_SHIPPED,
	RETURN_OUT_OF_DELIVERY,
	RETURN_DELIVERED

}
